### PR TITLE
New uitest for User List view for Admin role

### PR DESCRIPTION
**Pull request by palaparthi-ccpo**
Adding new test case to uitests for BrowserStack execution.  Tests a feature that lists users for users with the admin role.

Ticket: AT-6206

### CODE REVIEW

**Review by kylelaker-ccpo — COMMENTED** [review]
Not going to approve since I have commits in this PR but this looks good. I appreciate your work on this!

To other reviewers, this PR also fixes a bug in the tested implementation as well as assert introspection more generally for the UI tests.

**Comment by jasonburkert-ccpo** [comment]
Will review.

**Review by jasonburkert-ccpo — APPROVED** [review]
Peer reviewed.  Ran BrowserStackLocal tests successfully.  Looks good.

image


`pytest -s -v -m regression uitests/framework/test_cases/test_list_all_users_admin_role.py --no-cov --browser chrome --run-type BrowserStackLocal`

**Comment by jasonburkert-ccpo** [comment]
Despite the success above, `uitests/framework/README.md` needs some work, organizing content around one-time setup, and subsequent test execution using three terminals.

**Pull request merged**
