### PR TITLE
At 5946 remove public pages

### PR DESCRIPTION
**Pull request by jGonzalez-CCPO**
ticket: https://ccpo.atlassian.net/browse/AT-5946
doc: https://ccpo.atlassian.net/wiki/spaces/AT/pages/1296171468/AT-5946+-+Remove+unwanted+public-facing+pages

### CODE REVIEW

**Review by nkingsley-ccpo — CHANGES_REQUESTED** [review]
Rather than commenting these items out, we should just remove them, as since this project is stored in git we have a historical trail of what was added/removed and can revert these changes if it were ever needed.

**Comment by jGonzalez-CCPO** [comment]
> .

**Comment by jGonzalez-CCPO** [comment]
> Rather than commenting these items out, we should just remove them, as since this project is stored in git we have a historical trail of what was added/removed and can revert these changes if it were ever needed.

I agree, but that was explicitly asked on the ticket.

**Comment by jGonzalez-CCPO** [comment]
replaced by: https://github.com/dod-ccpo/atat/pull/2126/files

**Pull request closed without merging**
