### PR TITLE
Added tab index to the log in button

### PR DESCRIPTION
**Pull request by anhtran-ccpo**
Added tab index to the log in button in order to make it focusable through the keyboard
AT-5117

### CODE REVIEW

**Review by kylelaker-ccpo — CHANGES_REQUESTED** [review]
While this does make the button focusable, it does not make it so that the button can actually be triggered by the keyboard. Is there a reason this can't just be a `<button>`?  Or maybe the [button role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role)?

**Comment by anhtran-ccpo** [comment]
> While this does make the button focusable, it does not make it so that the button can actually be triggered by the keyboard. Is there a reason this can't just be a `<button>`? Or maybe the [button role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role)?

Just changed to a button to make it focusable and clickable through the keyboard. For some reason I thought it was already a button and I missed that. Thanks

**Review by kylelaker-ccpo — CHANGES_REQUESTED** [review]
If this is already covered under another ticket, that's all good and lmk. But now when you trigger the "Sign in with CAC" using the keyboard, you get the "You are accessing a USG IIS" and you can't "Continue" with the keyboard. Can we fix that button as well or create a ticket to do so? It's still impossible to login without a mouse from my experience.

**Comment by anhtran-ccpo** [comment]
> If this is already covered under another ticket, that's all good and lmk. But now when you trigger the "Sign in with CAC" using the keyboard, you get the "You are accessing a USG IIS" and you can't "Continue" with the keyboard. Can we fix that button as well or create a ticket to do so? It's still impossible to login without a mouse from my experience.

After digging into this for a bit. I found that the anchor tags do not interact with the space bar. Only the enter button is usable on anchor tags.

**Review by kylelaker-ccpo — APPROVED** [review]
Using Enter/Return does work on the "Continue" page. Looks good! Thanks for the clarification

**Pull request merged**
