### PR TITLE
Fixing run instructions to include the right host

### PR DESCRIPTION
**Pull request by jeffsegal-ccpo**

### CODE REVIEW

**Comment by anhtran-ccpo** [comment]
Is running against a non local instance simple as changing the host address to that server? i.e `demo.atat.dev`

**Review by kylelaker-ccpo — CHANGES_REQUESTED** [review]
I think there's some wonkiness with `host.docker.internal` with WSL2. Let me take a look this AM. But while I can resolve the hostname, the port doesn't seem to get forwarded to WSL2.

**Comment by jeffsegal-ccpo** [comment]
> Is running against a non local instance simple as changing the host address to that server? i.e `demo.atat.dev`

Yep

**Review by kylelaker-ccpo — APPROVED** [review]
Looks like I was wrong -- this works fine with WSL since it's all within Docker. Ran tests against `localhost` through Locust and everything worked fine.

**Pull request merged**
