### PR TITLE
Ensure seed_sample.py does not violate constraints

### PR DESCRIPTION
**Pull request by kylelaker-ccpo**
There have been some intermittent failures in the CI pipeline recently
because seed_sample.py would sometimes generate the same application
name twice within the same portfolio, which violates the database
constraints. This new code keeps "re-rolling" for a new name to ensure
that a unique one is always assigned to each application within a
portfolio.

Hopefully this prevents opaque unexpected error messages when running
tests.

Some unused imports were also removed.

### CODE REVIEW

**Comment by kylelaker-ccpo** [comment]
I suggest for these security hotspots, due to using `random.randint`, we use the same justification we have elsewhere. These are not used for cryptography; purely for generating random/seed data from static lists of items.

**Comment by kylelaker-ccpo** [comment]
Put this comment on each hotspot identified:
> This is used to generate sample data from static collections of data in development environments and for testing purposes. It is not used for cryptography or sensitive purposes. This usage is safe.

And for an example of the issue this solves:
<details>
<summary>Example log snippet of error</summary>
<pre>
2021-05-14T14:31:05.7078965Z /home/runner/work/atat/atat/atat/domain/permission_sets.py:45: SAWarning: relationship 'EnvironmentRole.application_role' will copy column application_roles.id to column environment_roles.application_role_id, which conflicts with relationship(s): 'ApplicationRole.environment_roles' (copies application_roles.id to environment_roles.application_role_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
2021-05-14T14:31:05.7084295Z   db.session.query(PermissionSet)
2021-05-14T14:31:05.7088927Z /home/runner/work/atat/atat/atat/domain/permission_sets.py:45: SAWarning: relationship 'Portfolio.clins' will copy column portfolios.id to column task_orders.portfolio_id, which conflicts with relationship(s): 'Portfolio.task_orders' (copies portfolios.id to task_orders.portfolio_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
2021-05-14T14:31:05.7095801Z   db.session.query(PermissionSet)
2021-05-14T14:31:05.7099860Z /home/runner/work/atat/atat/atat/domain/permission_sets.py:45: SAWarning: relationship 'Portfolio.clins' will copy column task_orders.id to column clins.task_order_id, which conflicts with relationship(s): 'CLIN.task_order' (copies task_orders.id to clins.task_order_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
2021-05-14T14:31:05.7103038Z   db.session.query(PermissionSet)
2021-05-14T14:31:05.7107903Z /home/runner/work/atat/atat/atat/domain/permission_sets.py:45: SAWarning: relationship 'TaskOrder.portfolio' will copy column portfolios.id to column task_orders.portfolio_id, which conflicts with relationship(s): 'Portfolio.task_orders' (copies portfolios.id to task_orders.portfolio_id), 'Portfolio.clins' (copies portfolios.id to task_orders.portfolio_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
2021-05-14T14:31:05.7111681Z   db.session.query(PermissionSet)
2021-05-14T14:31:05.7115691Z /home/runner/work/atat/atat/atat/domain/permission_sets.py:45: SAWarning: relationship 'TaskOrder.clins' will copy column task_orders.id to column clins.task_order_id, which conflicts with relationship(s): 'Portfolio.clins' (copies task_orders.id to clins.task_order_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
2021-05-14T14:31:05.7118884Z   db.session.query(PermissionSet)
2021-05-14T14:31:05.7123307Z /home/runner/work/atat/atat/atat/domain/permission_sets.py:45: SAWarning: relationship 'User.portfolio_invitations' will copy column users.id to column portfolio_invitations.user_id, which conflicts with relationship(s): 'PortfolioInvitation.user' (copies users.id to portfolio_invitations.user_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
2021-05-14T14:31:05.7126959Z   db.session.query(PermissionSet)
2021-05-14T14:31:05.7131387Z /home/runner/work/atat/atat/atat/domain/permission_sets.py:45: SAWarning: relationship 'User.sent_portfolio_invitations' will copy column users.id to column portfolio_invitations.inviter_id, which conflicts with relationship(s): 'PortfolioInvitation.inviter' (copies users.id to portfolio_invitations.inviter_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
2021-05-14T14:31:05.7134938Z   db.session.query(PermissionSet)
2021-05-14T14:31:05.7139275Z /home/runner/work/atat/atat/atat/domain/permission_sets.py:45: SAWarning: relationship 'User.application_invitations' will copy column users.id to column application_invitations.user_id, which conflicts with relationship(s): 'ApplicationInvitation.user' (copies users.id to application_invitations.user_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
2021-05-14T14:31:05.7142842Z   db.session.query(PermissionSet)
2021-05-14T14:31:05.7152442Z /home/runner/work/atat/atat/atat/domain/permission_sets.py:45: SAWarning: relationship 'User.sent_application_invitations' will copy column users.id to column application_invitations.inviter_id, which conflicts with relationship(s): 'ApplicationInvitation.inviter' (copies users.id to application_invitations.inviter_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
2021-05-14T14:31:05.7156234Z   db.session.query(PermissionSet)
2021-05-14T14:31:05.7157033Z Traceback (most recent call last):
2021-05-14T14:31:05.7160031Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
2021-05-14T14:31:05.7161162Z     self.dialect.do_execute(
2021-05-14T14:31:05.7162645Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
2021-05-14T14:31:05.7164070Z     cursor.execute(statement, parameters)
2021-05-14T14:31:05.7165314Z psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "applications_name_portfolio_id_key"
2021-05-14T14:31:05.7167138Z DETAIL:  Key (name, portfolio_id)=(Scalable Scalable, 79a19e0c-bc7f-4428-8e1e-2d1a7367638b) already exists.
2021-05-14T14:31:05.7167876Z 
2021-05-14T14:31:05.7168130Z 
2021-05-14T14:31:05.7168785Z The above exception was the direct cause of the following exception:
2021-05-14T14:31:05.7169318Z 
2021-05-14T14:31:05.7169808Z Traceback (most recent call last):
2021-05-14T14:31:05.7170747Z   File "/home/runner/work/atat/atat/atat/utils/__init__.py", line 41, in commit_or_raise_already_exists_error
2021-05-14T14:31:05.7171789Z     db.session.commit()
2021-05-14T14:31:05.7172411Z   File "<string>", line 2, in commit
2021-05-14T14:31:05.7173709Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
2021-05-14T14:31:05.7174749Z     self._transaction.commit(_to_root=self.future)
2021-05-14T14:31:05.7176112Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
2021-05-14T14:31:05.7177015Z     self._prepare_impl()
2021-05-14T14:31:05.7178259Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
2021-05-14T14:31:05.7179235Z     self.session.flush()
2021-05-14T14:31:05.7180462Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3262, in flush
2021-05-14T14:31:05.7181349Z     self._flush(objects)
2021-05-14T14:31:05.7182526Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3402, in _flush
2021-05-14T14:31:05.7183600Z     transaction.rollback(_capture_exception=True)
2021-05-14T14:31:05.7185037Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2021-05-14T14:31:05.7185966Z     compat.raise_(
2021-05-14T14:31:05.7188092Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2021-05-14T14:31:05.7189067Z     raise exception
2021-05-14T14:31:05.7190284Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3362, in _flush
2021-05-14T14:31:05.7191220Z     flush_context.execute()
2021-05-14T14:31:05.7192495Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 455, in execute
2021-05-14T14:31:05.7193433Z     rec.execute(self)
2021-05-14T14:31:05.7194654Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 629, in execute
2021-05-14T14:31:05.7195773Z     util.preloaded.orm_persistence.save_obj(
2021-05-14T14:31:05.7197353Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 242, in save_obj
2021-05-14T14:31:05.7198348Z     _emit_insert_statements(
2021-05-14T14:31:05.7199806Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1219, in _emit_insert_statements
2021-05-14T14:31:05.7200866Z     result = connection._execute_20(
2021-05-14T14:31:05.7202161Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
2021-05-14T14:31:05.7203413Z     return meth(self, args_10style, kwargs_10style, execution_options)
2021-05-14T14:31:05.7204927Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
2021-05-14T14:31:05.7206054Z     return connection._execute_clauseelement(
2021-05-14T14:31:05.7207510Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
2021-05-14T14:31:05.7208524Z     ret = self._execute_context(
2021-05-14T14:31:05.7209819Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
2021-05-14T14:31:05.7210804Z     self._handle_dbapi_exception(
2021-05-14T14:31:05.7212143Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
2021-05-14T14:31:05.7213136Z     util.raise_(
2021-05-14T14:31:05.7214303Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2021-05-14T14:31:05.7215195Z     raise exception
2021-05-14T14:31:05.7216440Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
2021-05-14T14:31:05.7217601Z     self.dialect.do_execute(
2021-05-14T14:31:05.7218930Z   File "/home/runner/work/atat/atat/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
2021-05-14T14:31:05.7219977Z     cursor.execute(statement, parameters)
2021-05-14T14:31:05.7221489Z sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "applications_name_portfolio_id_key"
2021-05-14T14:31:05.7223532Z DETAIL:  Key (name, portfolio_id)=(Scalable Scalable, 79a19e0c-bc7f-4428-8e1e-2d1a7367638b) already exists.
2021-05-14T14:31:05.7224265Z 
2021-05-14T14:31:05.7225407Z [SQL: INSERT INTO applications (claimed_until, name, description, portfolio_id, cloud_id) VALUES (%(claimed_until)s, %(name)s, %(description)s, %(portfolio_id)s, %(cloud_id)s) RETURNING applications.id]
2021-05-14T14:31:05.7227772Z [parameters: {'claimed_until': None, 'name': 'Scalable Scalable', 'description': 'whiteboard mission-critical functionalities', 'portfolio_id': UUID('79a19e0c-bc7f-4428-8e1e-2d1a7367638b'), 'cloud_id': None}]
2021-05-14T14:31:05.7229311Z (Background on this error at: http://sqlalche.me/e/14/gkpj)
2021-05-14T14:31:05.7229915Z 
2021-05-14T14:31:05.7230710Z During handling of the above exception, another exception occurred:
2021-05-14T14:31:05.7231257Z 
2021-05-14T14:31:05.7231751Z Traceback (most recent call last):
2021-05-14T14:31:05.7232485Z   File "./script/seed_sample.py", line 376, in <module>
2021-05-14T14:31:05.7233184Z     seed_db()
2021-05-14T14:31:05.7233804Z   File "./script/seed_sample.py", line 369, in seed_db
2021-05-14T14:31:05.7234652Z     add_applications_to_portfolio(portfolio)
2021-05-14T14:31:05.7235552Z   File "./script/seed_sample.py", line 241, in add_applications_to_portfolio
2021-05-14T14:31:05.7236401Z     application = Applications.create(
2021-05-14T14:31:05.7237339Z   File "/home/runner/work/atat/atat/atat/domain/applications.py", line 38, in create
2021-05-14T14:31:05.7238379Z     Environments.create_many(user, application, environment_names)
2021-05-14T14:31:05.7245948Z   File "/home/runner/work/atat/atat/atat/domain/environments.py", line 30, in create_many
2021-05-14T14:31:05.7247019Z     environment = Environments.create(user, application, name)
2021-05-14T14:31:05.7248071Z   File "/home/runner/work/atat/atat/atat/domain/environments.py", line 20, in create
2021-05-14T14:31:05.7249106Z     commit_or_raise_already_exists_error(message="environment")
2021-05-14T14:31:05.7250156Z   File "/home/runner/work/atat/atat/atat/utils/__init__.py", line 44, in commit_or_raise_already_exists_error
2021-05-14T14:31:05.7251096Z     raise AlreadyExistsError(message)
2021-05-14T14:31:05.7252209Z atat.domain.exceptions.AlreadyExistsError: environment
</pre>
</summary>

**Comment by kylelaker-ccpo** [comment]
https://github.com/dod-ccpo/atat/runs/2588111766 is a check that failed because of this bug.

**Review by anhtran-ccpo — APPROVED** [review]
Thanks for fixing this. This looks good.

**Pull request merged**
