### PR TITLE
Feature/AT-5906 Renamed ATST to ATAT

### PR DESCRIPTION
**Pull request by anhtran-ccpo**

### CODE REVIEW

**Review by jeffsegal-ccpo — APPROVED** [review]
Pulled the branch and could not find any atst or at-at references in the code. Did notice that the GI tests included comments with "AT-AT" but I am fine with ignoring those for now.

**Comment by nkingsley-ccpo** [comment]
Lets go ahead and pull out the .circleci directory for this, as that is no longer being used, and the changes that you made for that aren't needed anymore

**Comment by nkingsley-ccpo** [comment]
Once the circleci item is removed, this should be good to go

**Comment by anhtran-ccpo** [comment]
Circleci directory is removed

**Comment by jasonburkert-ccpo** [comment]
Agree this is now ready. 

As @jeffsegal-ccpo noted, only remaining thing I see is use of "AT-AT" in ./uitests which won't be address now.
[AT-AT-in-uitests.txt](https://github.com/dod-ccpo/atat/files/6004573/AT-AT-in-uitests.txt)

**Pull request merged**
