### PR TITLE
Fix bugs encountered during deployment

### PR DESCRIPTION
**Pull request by kylelaker-ccpo**
These are not necessarily permanent fixes but workarounds with the understanding that a lot of this code is already in the process of being refactored.

### CODE REVIEW

**Comment by kylelaker-ccpo** [comment]
Previous test failure was due to a non-deterministic test. Re-running tests.

**Comment by anhtran-ccpo** [comment]
> Previous test failure was due to a non-deterministic test. Re-running tests.

Do we have a ticket to clean this non deterministic test

**Comment by jasonburkert-ccpo** [comment]
> > Previous test failure was due to a non-deterministic test. Re-running tests.
> 
> Do we have a ticket to clean this non deterministic test

Yes.   I believe it is AT-5997.

**Review by jeffsegal-ccpo — APPROVED** [review]
Looks good to me, thanks again for catching these!

**Review by anhtran-ccpo — APPROVED** [review]

**Review by nkingsley-ccpo — APPROVED** [review]

**Review by jasonburkert-ccpo — APPROVED** [review]
Thumbs up.

**Pull request merged**
